target = "https://raw.githubusercontent.com/FoxIO-LLC/ja4/df3c067/technical_details/JA4.md#number-of-extensions"

# ### Number of Extensions:
#
# Same as counting ciphers. Ignore GREASE. Include SNI and ALPN.
# 

[[spec]]
level = "MUST"
quote = '''
Same as counting ciphers.
'''

[[spec]]
level = "MUST"
quote = '''
Ignore GREASE.
'''

[[spec]]
level = "MUST"
quote = '''
Include SNI and ALPN.
'''
