target = "https://www.rfc-editor.org/rfc/rfc8446#appendix-B"

# Appendix B.  Protocol Data Structures and Constant Values
#
# This appendix provides the normative protocol types and the
# definitions for constants.  Values listed as "_RESERVED" were used in
# previous versions of TLS and are listed here for completeness.
# TLS 1.3 implementations MUST NOT send them but might receive them
# from older TLS implementations.

[[spec]]
level = "MUST"
quote = '''
TLS 1.3 implementations MUST NOT send them but might receive them
from older TLS implementations.
'''

