target = "https://www.rfc-editor.org/rfc/rfc4492#section-5.2"

# 5.2.  Server Hello Extension
#
# This section specifies a TLS extension that can be included with the
# ServerHello message as described in [4], the Supported Point Formats
# Extension.
# 
# When this extension is sent:
# 
# The Supported Point Formats Extension is included in a ServerHello
# message in response to a ClientHello message containing the Supported
# Point Formats Extension when negotiating an ECC cipher suite.
# 
# Meaning of this extension:
# 
# This extension allows a server to enumerate the point formats it can
# parse (for the curve that will appear in its ServerKeyExchange
# message when using the ECDHE_ECDSA, ECDHE_RSA, or ECDH_anon key
# exchange algorithm, or for the curve that is used in the server's
# public key that will appear in its Certificate message when using the
# ECDH_ECDSA or ECDH_RSA key exchange algorithm).
# 
# Structure of this extension:
# 
# The server's Supported Point Formats Extension has the same structure
# as the client's Supported Point Formats Extension (see
# Section 5.1.2).  Items in elliptic_curve_list here are ordered
# according to the server's preference (favorite choice first).  Note
# that the server may include items that were not found in the client's
# list (e.g., the server may prefer to receive points in compressed
# format even when a client cannot parse this format: the same client
# may nevertheless be capable of outputting points in compressed
# format).
# 
# Actions of the sender:
# 
# A server that selects an ECC cipher suite in response to a
# ClientHello message including a Supported Point Formats Extension
# appends this extension (along with others) to its ServerHello
# message, enumerating the point formats it can parse.  The Supported
# Point Formats Extension, when used, MUST contain the value 0
# (uncompressed) as one of the items in the list of point formats.
# 
# Actions of the receiver:
# 
# A client that receives a ServerHello message containing a Supported
# Point Formats Extension MUST respect the server's choice of point
# formats during the handshake (cf. Sections 5.6 and 5.7).  If no
# Supported Point Formats Extension is received with the ServerHello,
# this is equivalent to an extension allowing only the uncompressed
# point format.

[[spec]]
level = "MUST"
quote = '''
The Supported
Point Formats Extension, when used, MUST contain the value 0
(uncompressed) as one of the items in the list of point formats.
'''

[[spec]]
level = "MUST"
quote = '''
A client that receives a ServerHello message containing a Supported
Point Formats Extension MUST respect the server's choice of point
formats during the handshake (cf.
'''

