[package]
name = "s2n-tls"
description = "A C99 implementation of the TLS/SSL protocols"
version = "0.3.26"
authors = ["AWS s2n"]
edition = "2021"
rust-version = "1.63.0"
repository = "https://github.com/aws/s2n-tls"
license = "Apache-2.0"

[features]
default = []
unstable-fingerprint = ["s2n-tls-sys/unstable-fingerprint"]
unstable-ktls = ["s2n-tls-sys/unstable-ktls"]
unstable-renegotiate = ["s2n-tls-sys/unstable-renegotiate"]
unstable-cert_authorities = ["s2n-tls-sys/unstable-cert_authorities"]
unstable-custom_x509_extensions = ["s2n-tls-sys/unstable-custom_x509_extensions"]
quic = ["s2n-tls-sys/quic"]
fips = ["s2n-tls-sys/fips"]
pq = ["s2n-tls-sys/pq"]
unstable-testing = []

[dependencies]
errno = { version = "0.3" }
# A minimum libc version of 0.2.121 is required by aws-lc-sys 0.14.0.
libc = "0.2.121"
s2n-tls-sys = { version = "=0.3.26", path = "../s2n-tls-sys", features = ["internal"] }
pin-project-lite = "0.2"
hex = "0.4"

[dev-dependencies]
futures-test = "0.3"
once_cell = "=1.20.3" # newer versions require rust 1.70.0
openssl = "0.10"
openssl-sys = "0.9"
foreign-types = "0.3" # newer versions require updated ForeignTypeRef, see https://github.com/sfackler/rust-openssl/issues/2298
temp-env = "0.3"
checkers = "0.6"
