[package]
name = "integration"
version = "0.1.0"
authors = ["AWS s2n"]
edition = "2021"
publish = false

[features]
default = ["pq", "no-network-tests"]

# Network tests are useful but relatively slow and inherently flaky. So they are
# behind this feature flag. This is specified as a "negative" feature because 
# many of our CI jobs use `cargo test --all-features`, and we don't want those
# to run these tests
no-network-tests = []

# Not all libcryptos support PQ capabilities. Tests relying on PQ functionality
# can be disabled by turning off this feature.
pq = [ "s2n-tls/pq" ]

[dependencies]
s2n-tls = { path = "../../extended/s2n-tls", features = ["unstable-testing"]}
s2n-tls-hyper = { path = "../s2n-tls-hyper" }
s2n-tls-tokio = { path = "../../extended/s2n-tls-tokio" }
s2n-tls-sys = { path = "../../extended/s2n-tls-sys" }
tls-harness = { path = "../tls-harness" }

[dev-dependencies]
openssl = { version = "0.10", features = ["vendored"] }
tokio = { version = "1", features = ["macros", "test-util"] }
tokio-openssl = { version = "0.6.5" }

tracing = "0.1"
tracing-subscriber = "0.3"
test-log = { version = "0.2", default-features = false, features = ["trace"]}

http = "1.1"
http-body-util = "0.1"
bytes = "1.8"
hyper = "1.5"
hyper-util = "0.1"

[build-dependencies]
# The ML-DSA tests require the ML-DSA support added in Openssl-3.5
# Since this overrides the dependency from the openssl-src crate,
# the features are copied from the openssl-src crate's Cargo.toml:
# https://github.com/sfackler/rust-openssl/blob/eb88fb0533c3593cc2fff6d03cf2befea8ecbe27/openssl-sys/Cargo.toml#L31
openssl-src = { version = "300.5", optional = true, features = ["legacy"] }
