[package]
name = "s2n-tls"
description = "A C99 implementation of the TLS/SSL protocols"
version = "0.0.4"
authors = ["AWS s2n"]
edition = "2018"
repository = "https://github.com/aws/s2n-tls"
license = "Apache-2.0"

[features]
default = []
quic = ["s2n-tls-sys/quic"]
pq = ["s2n-tls-sys/pq"]
testing = ["errno", "bytes"]

[dependencies]
bytes = { version = "1", optional = true }
errno = { version = "0.2", optional = true }
libc = "0.2"
s2n-tls-sys = { version = "=0.0.4", path = "../s2n-tls-sys", features = ["internal"] }

[dev-dependencies]
bytes = { version = "1" }
errno = { version = "0.2" }
futures-test = "0.3"
