name: OpenBSD

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  testopenbsd:
    runs-on: macos-12
    name: CI OpenBSD
    steps:
      - uses: actions/checkout@v3
      - name: Build and test in OpenBSD
        id: test
        uses: vmactions/openbsd-vm@v0.1.2
        with:
          mem: 2048
          prepare: |
            # The / (root) mount point in the VM doesn't have enough disk
            # space to build the project. These commands put the actual 'work'
            # directory in the /home mount (which has lots of disk space) and
            # creates symlinks to 'work' in the locations that the runner uses
            # when copying artifacts back and forth between the VM and macOS
            # host.
            mv /Users/runner /home
            rm -rf /Users
            ln -s /home /Users
            ln -sf /home/work /root/work
            pkg_add ninja cmake
            pkg_info
          run: |
            sysctl -n kern.version
            .github/s2n_openbsd.sh
      - name: upload test results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: all_test_output
          path: |
            release/testing/temporary
            build/testing/temporary
