---
name: dependencies

on:
  # Because of permissions issues with forked PRs,
  # Only run on a schedule or pushes to main.
  push:
    branches:
      - main
    # Only run if these files were touched.
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/dependencies.yml"

  schedule:
    # Run every day at 1800 UTC.
    - cron: "0 18 * * *"

env:
  ROOT_PATH: bindings/rust/extended

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write   # Open/update issues.
      checks: write   # Create/update a check run.
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        id: toolchain
        run: |
          rustup toolchain install stable
          rustup override set stable
      - uses: camshaft/rust-cache@v1
      - name: Generate
        run: ${{env.ROOT_PATH}}/generate.sh
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{env.ROOT_PATH}}
