---
name: macOS build and test S2n

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  OSX:
    runs-on: macos-latest
    steps:
      - name: Checkout Dependencies
        uses: actions/checkout@v5

      - name: Prebuild
        run: |
          .github/install_osx_dependencies.sh

      - name: Build
        run: |
          .github/s2n_osx.sh
